# Generated by Django 2.1.7 on 2019-03-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_comment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='author_like',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_post',
        ),
    ]
